#ifndef __DEFINES_H_
#define __DEFINES_H_

#define UP_BUTTON_DDR DDRC
#define UP_BUTTON_PORT PORTC
#define UP_BUTTON_PINREG PINC
#define UP_BUTTON_PIN 1

#define DOWN_BUTTON_DDR DDRC
#define DOWN_BUTTON_PORT PORTC
#define DOWN_BUTTON_PINREG PINC
#define DOWN_BUTTON_PIN 3

#define LEFT_BUTTON_DDR DDRC
#define LEFT_BUTTON_PORT PORTC
#define LEFT_BUTTON_PINREG PINC
#define LEFT_BUTTON_PIN 2

#define OK_BUTTON_DDR DDRC
#define OK_BUTTON_PORT PORTC
#define OK_BUTTON_PINREG PINC
#define OK_BUTTON_PIN 0

#define LCD_LED_DDR DDRD
#define LCD_LED_PORT PORTD
#define LCD_LED_PIN 7

#define LED_DDR DDRD
#define LED_PORT PORTD
#define LED_PIN 5

#define SPEAKER_DDR DDRD
#define SPEAKER_PORT PORTD
#define SPEAKER_PIN 6


#define SBM20_CONV_FACTOR 0.0057
#define DEFAULT_CONTRAST 0x3C

#define DEFAULT_BEEP_FREQ 3980

#define ALARM_TONE_1 5800
#define ALARM_TONE_2 7800


#define BEEP_LEN 10
#define DEFAULT_MEASURE_TIME 20
#define IDLE_REPAINT_HALFSECONDS 1

#define MKR_H "לך׀/ק"
#define MR_H "ל׀/ק"

#endif